---
- name: Obtain SSO token with username/password credentials
  ovirt_auth:
    url: "{{ ovirt_url }}"
    username: "{{ ovirt_username }}"
    password: "{{ ovirt_password }}"

- name: Deploy VM template
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: present
    cluster: "{{ OVIRT_CLUSTER }}"
    template: "{{ vm_template }}"
    name: "{{ vm_name }}"
    memory: "{{ vm_memory }}"
    cpu_sockets: 1
    cpu_cores: "{{ vm_cpu }}"
    type: server
    delete_protected: no
