---
- name: Obtain SSO token with username/password credentials
  ovirt_auth:
    url: "{{ OVIRT_URL }}"
    username: "{{ OVIRT_USERNAME }}@{{ OVIRT_DOMAIN }}"
    password: "{{ OVIRT_PASSWORD }}"

- name: Deploy VM template
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: present
    cluster: "{{ OVIRT_CLUSTER }}"
    template: "{{ vm_template }}"
    name: "{{ vm_name }}"
    memory: "{{ vm_memory }}"
    cpu_sockets: 1
    cpu_cores: "{{ vm_cpu }}"
    type: server
    delete_protected: no
